version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:

  pihole1:
    container_name: pihole1
    image: pihole/pihole:2023.03.0
    hostname: pihole-gr
    network_mode: host
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

    environment:
      TZ: "Europe/Paris"
      WEBPASSWORD: "YourVerySecurePasswordForAdminWebAccess"
      WEB_BIND_ADDR: "192.168.1.2"
      FTLCONF_LOCAL_IPV4: "192.168.1.2/32"
      PIHOLE_DNS_: "9.9.9.9;208.67.222.222;8.8.8.8;1.0.0.1"
      PIHOLE_PRIVACYLEVEL: "1"
      DHCP_ACTIVE: "true"
      DHCP_ROUTER: "192.168.1.1"
      DHCP_START: "192.168.1.10"
      DHCP_END: "192.168.1.99"
      PIHOLE_DOMAIN: local
      DHCP_IPv6: "false"
      IPv6: "false"
      TEMPERATUREUNIT: "c"
      QUERY_LOGGING: "false"

   volumes:
     - /home/pihole/volumes/etc-pihole:/etc/pihole
     - /home/pihole/volumes/etc-dnsmasq.d:/etc/dnsmasq.d
